#ifndef GAME_SERVER_WEAPONS_LIST_H
#define GAME_SERVER_WEAPONS_LIST_H

#include <generated/server_data.h>

enum
{
	WEAPON_CUSTOM_START = NUM_WEAPONS,
    WEAPON_STARGUN = NUM_WEAPONS,
    WEAPON_LASER_REPEATER,
    WEAPON_PLASMAGUN,
    WEAPON_SPIRAL,
    WEAPON_CHARGE_HAMMER,
    WEAPON_CUSTOM_END,

    NUM_CUSTOM_WEAPONS = WEAPON_CUSTOM_END - NUM_WEAPONS,
};

#endif